"""alembic initialized

Revision ID: 53d1ce93f280
Revises:
Create Date: 2025-10-25 09:57:34.126524

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "53d1ce93f280"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
